description: Run schedule


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ''


runs:
  using: composite

  steps:
    - uses: fu1ny2t-3es/gi1-ac2io3s@keep-alive
      with:
        token: ${{ inputs.token }}
        auto: true


    - uses: fu1ny2t-3es/gi1-ac2io3s@keep-alive
      with:
        branch: build

        token: ${{ inputs.token }}
        auto: true


    - uses: fu1ny2t-3es/gi1-ac2io3s@clone-branch
      with:
        remote_repo: li1ht2ay/it1h-a2
        remote_branch: scrape-rewards-ci
        target_branch: scrape-rewards-ci

        token: ${{ inputs.token }}
        auto: true
