on:
  workflow_dispatch:
  schedule:
    - cron: '45 1,7,13,19 * * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t/it1h-c2ai3@cron
        with:
          token: ${{ secrets.token }}
